[settings]
domain = "..."

[postgres]
server = "..."
port = 5432
username = "..."
password = "..."
db_name = "..."

[jwt]
key = "..."
lifetime_seconds = 86400 # 24*60*60
algorithm = "HS256"

[debug]
set = true
